### ISSUE TITLE
Create `pschema` files for the required datastes

### ISSUE THREAD

**Issue by PPrasai** [covidsimteam/prox-e#76]
**Feature Description:**
We need `pschema` files to represent data structures for the available datasets `arrivals`, `infected`, `quarantined`, `isolated`, `recovered` and `death`. We also need a `_meta` for each `pschema` which will include supporting information such as date.

**Comment by PPrasai** [comment]
I have a few more questions regarding these pschema files.
What should the _meta contain? I am guessing it should have a list of dates that correspond to the list of other info we will have.
Should we further granularize our pschemas to account for municipal level data (which we do not have yet). As of right now, our pschemas can only represent district level aggregations.

**Comment by risavkarna** [comment]
meta contains the following fields as relevant in the current context:

- geospatial data : geojson data about the origin location of the current data
- user: users who requested the data, created the data and last updated the data
- time: time of edits and new additions to the data since the data was first created
- review: reviewers and json records of past reviews and accepted review-based-changes
